<a href="https://colab.research.google.com/github/KacperLudwiczak/DL-Machine-Learning-Projects-Study/blob/main/Artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.11.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

# Ten fragment kodu wykorzystuje klasę LabelEncoder z biblioteki Scikit-learn (sklearn) do kodowania zmiennych kategorycznych w trzeciej kolumnie danych wejściowych X.
# Pierwsza linia importuje klasę LabelEncoder z modułu sklearn.preprocessing.
# Druga linia tworzy instancję klasy LabelEncoder i przypisuje ją do zmiennej le.
# Trzecia linia stosuje metodę fit_transform() obiektu le do trzeciej kolumny danych wejściowych X, co koduje zmienne kategoryczne na numeryczne etykiety. Zakodowane wartości zastępują oryginalne wartości kategoryczne w trzeciej kolumnie X.
# Należy zauważyć, że klasa LabelEncoder jest zwykle używana do kodowania zmiennych kategorycznych z dwoma lub więcej poziomami. Jeśli zmienna w trzeciej kolumnie X jest binarna, tzn. ma tylko dwa poziomy, możesz użyć klasy BinaryEncoder lub OneHotEncoder.

In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

# Ten fragment kodu wykorzystuje klasę ColumnTransformer z biblioteki Scikit-learn (sklearn) do przekształcenia jednej kolumny danych wejściowych X za pomocą klasy OneHotEncoder.
# Pierwsza linia importuje klasę ColumnTransformer i klasę OneHotEncoder z modułu sklearn.compose i sklearn.preprocessing.
# Druga linia tworzy instancję klasy ColumnTransformer i przypisuje ją do zmiennej ct. W argumencie transformers określa się listę krotek, w których pierwszym elementem jest nazwa transformatora (w tym przypadku 'encoder'), drugim elementem jest instancja transformatora (OneHotEncoder()), a trzecim elementem jest indeks kolumny (1), którą chcemy przekształcić.
# Trzecia linia stosuje metodę fit_transform() obiektu ct do danych wejściowych X, co przekształca kolumnę indeksowaną przez 1 na macierz binarną (dummy matrix) z kodowaniem "jedynkowym" (one-hot encoding). Argument remainder='passthrough' powoduje, że pozostałe kolumny danych wejściowych są przekazywane bez zmian.
# Czwarta linia przypisuje nową przetworzoną macierz danych X do zmiennej X, która jest typu ndarray.

# Każda z funkcji użyta w powyższych kodach ma swoje specyficzne zastosowanie.
# Funkcja LabelEncoder z biblioteki Scikit-learn jest używana do kodowania zmiennych kategorycznych z dwoma lub więcej poziomami na wartości numeryczne. Dzięki temu można przekształcić dane kategoryczne na format, który może być używany przez algorytmy uczenia maszynowego, które wymagają danych numerycznych.
# Funkcja OneHotEncoder z biblioteki Scikit-learn służy do kodowania zmiennych kategorycznych w taki sposób, aby stworzyć macierz binarną, która reprezentuje każde z wartości kategorycznych jako wektor 0/1. Ten sposób kodowania umożliwia zachowanie pełnej informacji o danych kategorycznych, ale zwiększa rozmiar zbioru danych.
# Klasa ColumnTransformer z biblioteki Scikit-learn pozwala na przekształcanie różnych kolumn w różny sposób, np. zastosowanie różnych transformatorów na różnych kolumnach. W powyższym kodzie wykorzystano ją, aby przekształcić tylko jedną kolumnę danych, pozostawiając pozostałe kolumny bez zmian.
# W zależności od potrzeb i charakterystyki danych, różne funkcje i klasy z biblioteki Scikit-learn mogą być stosowane w celu przetwarzania i transformacji danych przed ich wykorzystaniem w algorytmach uczenia maszynowego.

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

# Ten fragment kodu tworzy instancję klasy Sequential z biblioteki TensorFlow Keras.
# Obiekt tej klasy służy do tworzenia sekwencyjnych modeli sieci neuronowych, w których warstwy są układane jedna po drugiej w kolejności, w jakiej są definiowane. To znaczy, wyjście jednej warstwy jest wejściem do następnej warstwy.
# W sekwencyjnym modelu każda warstwa sieci neuronowej ma dokładnie jeden tensor wejściowy i jeden tensor wyjściowy. Przykładowo, sekwencyjny model może składać się z kilku warstw konwolucyjnych, warstw MaxPooling, warstw Dropout, warstw Flatten i warstwy w pełni połączonej (Dense).
# Po utworzeniu instancji Sequential można dodawać kolejne warstwy do modelu, używając metody add(). W ten sposób tworzymy model sieci neuronowej, który można trenować i oceniać na danych.

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Ten fragment kodu dodaje do modelu sekwencyjnego warstwę Dense z biblioteki TensorFlow Keras.
# Dense to klasa, która reprezentuje w pełni połączoną (ang. fully connected) warstwę sieci neuronowej, w której każdy neuron z poprzedniej warstwy jest połączony z każdym neuronem w kolejnej warstwie.
# Argument units=6 określa liczbę neuronów w warstwie. W tym przypadku warstwa będzie miała 6 neuronów.
# Argument activation='relu' określa funkcję aktywacji, która będzie stosowana w warstwie. W tym przypadku funkcją aktywacji jest ReLU (Rectified Linear Unit), która zwraca wartość maksymalną z zera i argumentu funkcji. Jest to jedna z popularnych funkcji aktywacji stosowanych w sieciach neuronowych.
# Dodanie tej warstwy do modelu sekwencyjnego powoduje, że wyjście poprzedniej warstwy staje się wejściem do nowo dodanej warstwy. W ten sposób można budować sieci neuronowe o złożonej strukturze, w których każda kolejna warstwa przetwarza wynik poprzedniej warstwy.

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Ten fragment kodu dodaje do modelu sekwencyjnego kolejną warstwę Dense z biblioteki TensorFlow Keras.
# W tym przypadku argument units=1 określa liczbę neuronów w warstwie, co oznacza, że wyjście z tej warstwy będzie składać się z jednej wartości.
# Argument activation='sigmoid' określa funkcję aktywacji, która będzie stosowana w warstwie. W tym przypadku funkcją aktywacji jest sigmoida, która zwraca wartość w zakresie [0,1]. Jest to popularna funkcja aktywacji stosowana w warstwach wyjściowych sieci neuronowych, gdy chcemy uzyskać wynik w postaci prawdopodobieństwa.
# W ten sposób, po dodaniu tej warstwy do modelu sekwencyjnego, otrzymujemy sieć neuronową, która przetwarza wejście i zwraca jedno wyjście w postaci wartości prawdopodobieństwa. Ta sieć neuronowa może być wykorzystana do rozwiązywania problemów binarnej klasyfikacji, gdzie chcemy przewidzieć jedną z dwóch możliwych kategorii.

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics= ['accuracy'])

# Gdybym niechciał binary, bo chce wiecej niż dwa kategorie to użyje 'categorical_crossentropy', również zmieniam 'sigmoid' na 'softmax' w Output Layer!!!

# Ten fragment kodu kompiluje sieć neuronową ann utworzoną wcześniej za pomocą metody compile() z biblioteki TensorFlow Keras.
# Argument optimizer='adam' określa algorytm optymalizacji, który będzie używany podczas trenowania sieci neuronowej. W tym przypadku używany jest algorytm Adam, który jest popularnym algorytmem optymalizacji stosowanym w sieciach neuronowych.
# Argument loss='binary_crossentropy' określa funkcję straty (ang. loss function), która będzie minimalizowana podczas trenowania sieci neuronowej. W tym przypadku używana jest funkcja straty binarnej entropii krzyżowej, która jest popularną funkcją straty stosowaną w problemach binarnej klasyfikacji.
# Argument metrics=['accuracy'] określa miary jakości, które będą wykorzystane do oceny wyników sieci neuronowej podczas trenowania i testowania. W tym przypadku używana jest miara dokładności (ang. accuracy), która określa procent poprawnych predykcji klasy.

### Training the ANN on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

# Ten fragment kodu trenuje sieć neuronową ann, która została utworzona wcześniej za pomocą metody fit() z biblioteki TensorFlow Keras.
# Argument X_train i y_train to dane treningowe, które są używane do trenowania sieci neuronowej. Dane te muszą być zgodne z wymaganiami określonymi przez model sieci neuronowej.
# Argument batch_size=32 określa rozmiar batcha, czyli liczba próbek, które są przetwarzane jednocześnie przez sieć neuronową w jednej iteracji podczas trenowania. W tym przypadku wykorzystywany jest batch o rozmiarze 32 próbek.
# Argument epochs=100 określa liczbę epok, czyli liczbę razy, jakie sieć neuronowa będzie trenowana na całym zbiorze treningowym. W tym przypadku sieć neuronowa będzie trenowana przez 100 epok.
# Podczas trenowania sieci neuronowej model jest optymalizowany w celu minimalizacji funkcji straty określonej podczas kompilacji sieci. Po każdej epoce wyniki są oceniane za pomocą wybranych wcześniej miar jakości, w tym przypadku dokładności (accuracy), aby sprawdzić, jak dobrze sieć neuronowa generalizuje na danych treningowych.

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.6116 - accuracy: 0.7523
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4712 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4457 - accuracy: 0.7964
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4354 - accuracy: 0.7981
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4277 - accuracy: 0.8100
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4212 - accuracy: 0.8174
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4149 - accuracy: 0.8198
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4093 - accuracy: 0.8238
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4046 - accuracy: 0.8254
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4008 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

In [ ]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

# Ten fragment kodu wykorzystuje wytrenowaną sieć neuronową ann, aby dokonać predykcji na nowych danych. Do predykcji wykorzystywana jest metoda predict() z biblioteki TensorFlow Keras.
# Argument sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]) przekształca nowe dane wejściowe do skali, która została wykorzystana podczas uczenia sieci neuronowej. W tym przypadku wykorzystywany jest wcześniej utworzony obiekt sc klasy StandardScaler z biblioteki scikit-learn.
# Operator > 0.5 określa próg decyzyjny, powyżej którego predykcja zostanie sklasyfikowana jako pozytywna (1), a poniżej którego predykcja zostanie sklasyfikowana jako negatywna (0).
# W tym przypadku wynik predykcji jest wyświetlany w postaci wartości logicznej True lub False, w zależności od wyniku porównania z progiem decyzyjnym.

1/1 [==============================] - 0s 320ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1501   94]
 [ 188  217]]


0.859